name: unit_auto
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

#--------------- PACKAGES ---------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  image_picker: ^1.1.1
  url_launcher: ^6.2.6
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^5.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  

  # Product Specific
  carousel_slider: ^4.2.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.4
  cached_network_image: ^3.3.1


  #--------------- ./ PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true


  #--------------- LOCAL ASSETS ---------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/signup_images/
    - assets/images/banner_car/
    - assets/images/user/
    - assets/images/home/
    - assets/images/animations/

  #--------------- LOCAL FONTS ---------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins-Italic.ttf
          style: italic
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800

